name: "GitHub Actions WebDeploy"
description: "Deploy a WebApp to IIS"
author: "nhatthai"
branding:
  icon: upload-cloud
  color: blue
inputs:
  server:
    description: "IP or ComputerName server remotely"
    required: true
  app_name:
    description: "IIS App name"
    required: true
  app_pool_name:
    description: "Application Pool Name"
    required: true
  physical_path:
    description: "The path to the destination directory that will be deployed"
    required: true
  deploy_user_id:
    description: "UserName login the remote server"
    required: true
  deploy_user_secret:
    description: "Password login the remote server"
    required: true
  website_name:
    description: "IIS website name"
  app_pool_user_service:
    description: "User Service Account"
  app_pool_password_service:
    description: "Password Service Account"
runs:
  using: "composite"
  steps:
    - name: Deploy Web Application
      shell: powershell
      run: >
        ${{ github.action_path }}/scripts/iss_action.ps1
        '${{ inputs.server }}'
        '${{ inputs.app_name }}'
        '${{ inputs.app_pool_name }}'
        '${{ inputs.physical_path }}'
        '${{ inputs.deploy_user_id }}'
        '${{ inputs.deploy_user_secret }}'
        '${{ inputs.website_name }}'
        '${{ inputs.app_pool_user_service }}'
        '${{ inputs.app_pool_password_service }}'