name: "GitHub Actions WebDeploy"
description: "Deploy a WebApp to IIS"
author: "nhatthai"
branding:
  icon: upload-cloud
  color: blue
inputs:
  website_name:
    description: "IIS website name"
    required: true
  app_name:
    description: "IIS App name"
    required: true
  app_pool_name:
    description: "Application Pool Name"
    required: true
  physical_path:
    description: "The path to the source directory that will be deployed"
    required: true
runs:
  using: "composite"
  steps:
    - name: Deploy Web Application
      shell: powershell
      run: >
        ${{ github.action_path }}/scripts/iss_action.ps1
        ${{ inputs.website_name }}
        ${{ inputs.app_name }}
        ${{ inputs.app_pool_name }}
        ${{ inputs.physical_path }}